### ISSUE TITLE
How do I build a real time orderbook ?

### ISSUE THREAD

**Issue by szd116** [CCob/bittrex4j#18]
I would assume first I need to poll a snapshot of the market oderbook by doing this;
 BittrexExchange bittrexExchange = new BittrexExchange();
 Response<MarketOrdersResult> markets = bittrexExchange.getMarketOrderBook("USDT-BTC");
for (MarketOrder ele : markets.getResult().getBuys())
System.out.println(" "+ele.getRate() + "size:" + ele.getQuantity());

But this orderbook snapshot doesn't give any sequence number or timestamp, so when the web socket live data come in, how do I know if the web socket data is the latest than this snapshot ? can someone please provide an example ?

**Comment by CCob** [comment]
You cant use the REST API to build a real time order book.  You need to use the websocket logic.  Once the connected callback is called you subscribeToExchangeDeltas, once this succeeds you make a call to queryExchangeState.  You then must capture the deltas so that you can apply the ones ontop of the results from the full queryExchangeState.

**Comment by CCob** [comment]
queryExchangeState is not meant to be called in a loop and your ip will be banned if you so only use it on first connect or when you lose sync of deltas and need to resync

**Comment by szd116** [comment]
Thank you very much for your reply. I've got this to work. Great job on the API, please keep up the good work.

**Comment by CCob** [comment]
Great.  Glad to help.
